# Generated by Django 2.0.4 on 2018-04-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_number', models.CharField(max_length=8, verbose_name='DNI')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido')),
                ('gender', models.CharField(choices=[('M', 'Mascúlino'), ('F', 'Femenino')], max_length=2)),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monto Solicitado')),
            ],
        ),
    ]
