# Generated by Django 2.0.4 on 2018-04-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_number', models.CharField(max_length=8, verbose_name='DNI')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido')),
                ('gender', models.CharField(choices=[('M', 'Mascúlino'), ('F', 'Femenino')], max_length=2)),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.RemoveField(
            model_name='loan',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='mail',
        ),
        migrations.AddField(
            model_name='loan',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01', verbose_name='Fecha Solicitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Solicitado'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user_loan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loans.UserLoan'),
            preserve_default=False,
        ),
    ]
