# Generated by Django 2.0.4 on 2018-04-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20180417_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='legal_number',
        ),
    ]
